/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Stays 200 during a graceful shutdown so the orchestrator lets the process drain.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Liveness"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports 503 as soon as a shutdown begins, so traffic drains before connections close.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dependencies reachable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Readiness"];
                    };
                };
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a session
         * @description Rate limited to 10/minute per IP, and fails closed in production: if Redis is unavailable this returns 503 rather than waving brute-force attempts through. Unknown and known emails take the same time.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The current user
         * @description What a client calls when restoring a session on boot. Any authenticated staff role.
         *
         *     **Use this rather than /auth/refresh to identify the caller.** Refresh *rotates*: two tabs
         *     starting at once both present the same stored token, one claims it, and the other is
         *     treated as theft and revokes every session for that user. Calling refresh merely to ask
         *     "who am I" turns a second browser tab into a logout.
         *
         *     Read from the database rather than the token, so a deactivated account stops working
         *     inside the access token's fifteen minutes rather than at the end of them.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Rotation is atomic. Presenting an already-revoked token is treated as theft and revokes every session for that user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New session issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh session
         * @description Always 204, so it never reveals whether the token was valid.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Revoked, or the token was already invalid. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a signed table QR for a guest session
         * @description The QR nonce is checked against the table, so a rotated or reprinted code stops working immediately.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GuestSessionRequest"];
                };
            };
            responses: {
                /** @description Guest session created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GuestSession"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        /**
         * End a guest session
         * @description Always 204, whether or not the session existed, so it never confirms that a given session id was live.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ended, or it was already gone. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/bill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The open bill for the guest's own table
         * @description Authenticated with a guest session: `X-Guest-Session` plus the guest token as a bearer.
         *
         *     **Takes no bill id.** The table comes from the session, which came from a signed QR, so
         *     a guest cannot request a bill that is not theirs -- there is no identifier to tamper with.
         *
         *     Returns 404 when the table has no open bill, which is the normal state between sittings.
         *
         *     Rate limited to 30 requests a minute per IP.
         */
        get: operations["getGuestBill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/bill/split/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split the guest's own bill
         * @description The same engine the staff endpoint uses, so a diner and a waiter looking at one bill are
         *     never shown two different allocations. **Advisory: it moves no money.**
         *
         *     Scoped to the session's table, like every guest route.
         */
        post: operations["previewGuestSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/tables/{tableId}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mint a signed QR token for a table
         * @description Roles: OWNER, MANAGER. The table is resolved inside the caller's restaurant.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tableId: components["parameters"]["TableId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed QR token. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QrToken"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/tables/{tableId}/qr/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a table QR nonce
         * @description Roles: OWNER, MANAGER. Invalidates every QR previously printed for the table.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tableId: components["parameters"]["TableId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rotated. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tables
         * @description Any authenticated staff role.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    active?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tables. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TableList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * Create a table
         * @description Roles: OWNER, MANAGER.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTableRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Table"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a table
         * @description Roles: OWNER, MANAGER. Partial update; at least one field is required.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tableId: components["parameters"]["TableId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTableRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Table"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/api/v1/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bills
         * @description Any authenticated staff role. Scoped to the caller's restaurant.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    status?: "OPEN" | "CLOSED" | "VOID";
                    tableId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bills. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * Open a bill for a table
         * @description Roles: OWNER, MANAGER, CASHIER, WAITER. A table may have only one OPEN bill; a second attempt returns 409 `OPEN_BILL_EXISTS` with the existing bill id.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBillRequest"];
                };
            };
            responses: {
                /** @description Bill opened. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/tables/{tableId}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a table to its current open bill
         * @description What a client scanning a permanent table QR calls. Any authenticated staff role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tableId: components["parameters"]["TableId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The open bill. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a bill
         * @description Any authenticated staff role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["BillId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The bill, with its line items. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillWithItems"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the lines on a bill
         * @description Any authenticated staff role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["BillId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lines. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillItemList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * Add a line to a bill
         * @description Roles: OWNER, MANAGER, CASHIER, WAITER.
         *
         *     The product name and price are **snapshotted** onto the line, so later menu changes
         *     never alter a bill already served. Adding the same product twice creates two lines: a
         *     second round may have been ordered at a different price.
         *
         *     The bill total is recomputed from its lines and re-converted at the rate **frozen when
         *     the bill opened**, never at the current rate.
         *
         *     Only an OPEN bill accepts lines. A bill opened with a fixed non-zero total is refused
         *     with 409 `BILL_NOT_ITEMISED`; open it with a total of 0 to itemise it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["BillId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddBillItemRequest"];
                };
            };
            responses: {
                /** @description Line added. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillItemMutation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a line from a bill
         * @description Roles: OWNER, MANAGER, CASHIER, WAITER.
         *
         *     Refused with 409 `TOTAL_BELOW_AMOUNT_PAID` when it would drop the bill total below what
         *     has already been settled — reversing money that has moved is a refund, not an edit.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["BillId"];
                    itemId: components["parameters"]["BillItemId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillItemRemoval"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Change a line quantity
         * @description Roles: OWNER, MANAGER, CASHIER, WAITER. The snapshotted unit price is never revisited; only the quantity changes.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["BillId"];
                    itemId: components["parameters"]["BillItemId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBillItemRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillItemMutation"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/api/v1/bills/{id}/split/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute an exact split of the outstanding balance
         * @description Any authenticated staff role. **Advisory: this mutates nothing.** Payment still goes
         *     through the payments endpoint, which holds the bill lock and enforces the ceiling.
         *
         *     **Every mode divides the same figure** — the outstanding VES balance — echoed back as
         *     `outstandingVes`, so a client never has to work out which number was split.
         *
         *     Allocation is largest-remainder, so the parts sum to exactly the total. Rounding each
         *     share independently would leave the last diner unable to pay under
         *     `CHECK (amount_paid_ves <= total_due_ves)`. `totalAllocatedVes` is returned so a client
         *     can assert that rather than trust it.
         *
         *     POST because the intent does not fit in a query string, not because anything is written.
         */
        post: operations["previewSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Void an unpaid bill
         * @description Roles: OWNER, MANAGER. Refused once any payment has been applied: reversing money that has moved is a refund, not a status change.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["BillId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Voided. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a payment to a bill
         * @description Settlement is **always VES**. USD appears in the response as a display reference only.
         *
         *     **Roles:** OWNER, MANAGER, CASHIER.
         *
         *     **Idempotency.** Supply `Idempotency-Key` (or `idempotencyKey` in the body). Replaying a
         *     completed key returns the stored response rather than charging again. Reusing a key with a
         *     different payload, or while the first request is still in flight, is a 409.
         *
         *     **Concurrency.** The bill row is locked for the duration, so simultaneous splits serialise
         *     and cannot overpay. The display rate was frozen when the bill was opened, so every
         *     split reports the same figure and nothing drifts mid-meal.
         *
         *     **FX is never load-bearing.** If no verified rate is available the payment still applies and
         *     the USD reference is null.
         *
         *     **Rate limited** to 60/minute per authenticated user.
         */
        post: operations["applyPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Official BCV reference rates (USD and EUR)
         * @description Presentational. Returns 503 rather than a stale or invented rate when none is in force; payments are unaffected either way.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rate in force. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeRate"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
                503: components["responses"]["ServiceUnavailable"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/public/{restaurantId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public menu for a restaurant
         * @description Unauthenticated: a guest scanning a table QR holds no staff credentials.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    restaurantId: components["parameters"]["RestaurantId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active menu. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicMenu"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Restaurant menu settings
         * @description Any authenticated staff role.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Settings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/settings/currency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the menu currency
         * @description Roles: OWNER, MANAGER. Refused with 409 `MENU_CURRENCY_MISMATCH` while any active product is still priced in the old currency; prices are never converted automatically.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MenuCurrencyRequest"];
                };
            };
            responses: {
                /** @description Changed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuSettings"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/api/v1/menu/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List menu products
         * @description Any authenticated staff role.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    active?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Products. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductList"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        /**
         * Create a menu product
         * @description Roles: OWNER, MANAGER. The currency comes from the restaurant, not the request.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProductRequest"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deactivate a menu product
         * @description Roles: OWNER, MANAGER. A soft delete: a bill already referencing the product must stay readable.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProductId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a menu product
         * @description Roles: OWNER, MANAGER. Partial update; at least one field is required.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProductId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProductRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Product"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                429: components["responses"]["TooManyRequests"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @description Stable identifier for what went wrong. Branch on this, never on `message`. A code always carries the same HTTP status.
                 * @enum {string}
                 */
                code: "VALIDATION_FAILED" | "BILL_ID_MISMATCH" | "INVALID_AMOUNT" | "INVALID_MONETARY_VALUE" | "WEBHOOK_BODY_UNVERIFIABLE" | "SPLIT_PARTICIPANTS_INVALID" | "SPLIT_CLAIMS_INCOMPLETE" | "SPLIT_CLAIM_UNKNOWN" | "SPLIT_AMOUNT_MISMATCH" | "AUTH_TOKEN_MISSING" | "AUTH_TOKEN_INVALID" | "INVALID_CREDENTIALS" | "GUEST_SESSION_MISSING" | "GUEST_SESSION_INVALID" | "QR_INVALID" | "WEBHOOK_SIGNATURE_MISSING" | "WEBHOOK_SIGNATURE_INVALID" | "WEBHOOK_TIMESTAMP_OUT_OF_TOLERANCE" | "FORBIDDEN_ROLE" | "CROSS_TENANT_DENIED" | "CORS_ORIGIN_NOT_ALLOWED" | "NOT_FOUND" | "BILL_NOT_FOUND" | "BILL_ITEM_NOT_FOUND" | "TABLE_NOT_FOUND" | "PRODUCT_NOT_FOUND" | "RESTAURANT_NOT_FOUND" | "OPEN_BILL_NOT_FOUND" | "OPEN_BILL_EXISTS" | "BILL_NOT_OPEN" | "BILL_NOT_ITEMISED" | "TOTAL_BELOW_AMOUNT_PAID" | "PRODUCT_INACTIVE" | "SPLIT_NOT_ITEMISED" | "SPLIT_NOTHING_OUTSTANDING" | "BILL_HAS_PAYMENTS" | "PAYMENT_EXCEEDS_BALANCE" | "PAYMENT_STATE_INVALID" | "IDEMPOTENCY_KEY_REUSED" | "IDEMPOTENCY_IN_FLIGHT" | "TABLE_NAME_TAKEN" | "PRODUCT_NAME_TAKEN" | "MENU_CURRENCY_MISMATCH" | "WEBHOOK_ALREADY_PROCESSED" | "RATE_LIMITED" | "RATE_LIMITER_UNAVAILABLE" | "FX_UNAVAILABLE" | "WEBHOOK_REPLAY_PROTECTION_UNAVAILABLE" | "SHUTTING_DOWN" | "INTERNAL_ERROR";
                /** @description Human-readable and subject to change without notice. Never parse it. 5xx messages are always the literal string "Internal Server Error". */
                message: string;
                /** @description Structured context for this code, always present and possibly empty. See x-error-details for what each code carries. */
                details: {
                    [key: string]: unknown;
                };
                /** @description Correlates with the server log line for this failure. Quote it in bug reports. */
                requestId: string;
            };
        };
        ValidationError: components["schemas"]["Error"] & {
            error?: {
                details?: {
                    fields?: string[];
                };
            };
        };
        Bill: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            restaurantId?: string;
            /** Format: uuid */
            tableId?: string;
            /** @enum {string} */
            status?: "OPEN" | "CLOSED" | "VOID";
            /**
             * @description Sum of the line items, before charges.
             * @example 756710
             */
            subtotalMinor?: string;
            /** @description IVA rate in basis points, frozen when the bill opened. 1600 = 16%. */
            vatBps?: number;
            /**
             * @description IVA, taken on the subtotal alone — never on the service charge.
             * @example 756710
             */
            vatMinor?: string;
            /** @description Servicio rate in basis points, frozen when the bill opened. 1000 = 10%. */
            serviceChargeBps?: number;
            /**
             * @description Servicio, taken on the subtotal. Not taxed.
             * @example 756710
             */
            serviceChargeMinor?: string;
            /**
             * @description subtotalMinor + vatMinor + serviceChargeMinor, in the menu currency. The database refuses a row where those disagree.
             * @example 756710
             */
            totalDue?: string;
            /**
             * @description The currency the menu quoted. Settlement is always VES.
             * @enum {string}
             */
            currency?: "VES" | "USD" | "EUR";
            /**
             * @description Authoritative amount to settle.
             * @example 756710
             */
            totalDueVes?: string;
            /**
             * @description Authoritative amount settled so far.
             * @example 756710
             */
            amountPaidVes?: string;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            remainingVes?: string;
            /**
             * @description VES per unit of menu currency, padded to 8 decimal places. Frozen when the bill was opened.
             * @example 757.54060000
             */
            fxRateVesPerUnit?: string | null;
            fxRateSource?: string | null;
            /**
             * Format: date
             * @description Calendar date only. Never a timestamp: a zone offset here can shift the BCV value date by a day.
             * @example 2025-03-06
             */
            fxValueDate?: string | null;
            calculationVersion?: number;
            usdReference?: components["schemas"]["UsdReference"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description A line on a bill. The price is snapshotted when the line is added, so re-pricing, renaming or deactivating the product never changes a bill already served. */
        BillItem: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            billId?: string;
            /**
             * Format: uuid
             * @description Reporting link only. Null once the product is gone; the line outlives it.
             */
            productId?: string | null;
            /** @description The product name as it was when the line was added. */
            name?: string;
            /**
             * @description Snapshotted unit price, in the bill currency.
             * @example 756710
             */
            unitPriceMinor?: string;
            /** @enum {string} */
            currency?: "VES" | "USD" | "EUR";
            quantity?: number;
            /**
             * @description unitPriceMinor x quantity, computed by the database.
             * @example 756710
             */
            subtotalMinor?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BillWithItems: components["schemas"]["Bill"] & {
            itemCount?: number;
            items?: components["schemas"]["BillItem"][];
        };
        BillItemList: {
            data?: components["schemas"]["BillItem"][];
        };
        /** @description The affected line and the recalculated bill, so a client never re-derives a total. */
        BillItemMutation: {
            item?: components["schemas"]["BillItem"];
            bill?: components["schemas"]["Bill"];
        };
        BillItemRemoval: {
            /** Format: uuid */
            removedId?: string;
            bill?: components["schemas"]["Bill"];
        };
        AddBillItemRequest: {
            /** Format: uuid */
            productId: string;
            /** @default 1 */
            quantity: number;
        };
        UpdateBillItemRequest: {
            quantity: number;
        };
        /** @description Presentational only. Null throughout when no verified rate was available; settlement is unaffected. */
        UsdReference: {
            totalDue?: string | null;
            amountPaid?: string | null;
            remaining?: string | null;
        };
        BillList: {
            data?: components["schemas"]["Bill"][];
            limit?: number;
            offset?: number;
        };
        CreateBillRequest: {
            /** Format: uuid */
            tableId: string;
            /**
             * @description Minor units in the restaurant menu currency, which the bill inherits.
             * @example 756710
             */
            totalDueMinorUnits: string;
        };
        PaymentRequest: {
            /**
             * Format: uuid
             * @description Must equal the id in the path; a mismatch is a 400.
             */
            billId: string;
            /**
             * @description VES céntimos as a digit string, so a payment can be as large as the column holds. A JSON number is accepted for convenience but is rejected beyond 2^53, where it has already lost precision.
             * @example 250000
             */
            amountMinorUnits: string;
            /**
             * @description Settlement is VES only. USD appears in responses as a reference, never as a payment.
             * @constant
             */
            currency: "VES";
            /** @description Used when the Idempotency-Key header is absent. */
            idempotencyKey: string;
        };
        PaymentResult: {
            /** Format: uuid */
            id?: string;
            /**
             * Format: uuid
             * @description The ledger row this payment created.
             */
            paymentId?: string;
            /** @enum {string} */
            status?: "OPEN" | "CLOSED";
            /** @constant */
            currency?: "VES";
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            totalDue?: string;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            amountPaid?: string;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            remaining?: string;
            /** @enum {string} */
            displayCurrency?: "VES" | "USD" | "EUR";
            /**
             * @description VES per unit of display currency, padded to 8 decimal places.
             * @example 757.54060000
             */
            fxRate?: string | null;
            fxSource?: string | null;
            usdReference?: components["schemas"]["UsdReference"];
        };
        SplitPreviewRequest: {
            /**
             * @description FULL: one participant owes the balance. EQUAL: divided evenly. ITEMS: participants claim lines, shared lines split between claimants. CUSTOM: the client states amounts, which must add up exactly.
             * @enum {string}
             */
            mode: "FULL" | "EQUAL" | "ITEMS" | "CUSTOM";
            participants: {
                /** @description Client-owned and opaque to the server. Must be unique within the request. */
                id: string;
                name?: string;
                /**
                 * @description CUSTOM only. Must sum to outstandingVes exactly.
                 * @example 756710
                 */
                amountVes?: string;
            }[];
            /** @description ITEMS only. Every line on the bill must appear, or the split is refused. */
            claims?: {
                /** Format: uuid */
                itemId: string;
                /** @description More than one splits that line evenly between them. */
                participantIds: string[];
            }[];
        };
        SplitPreview: {
            /** Format: uuid */
            billId?: string;
            /** @enum {string} */
            mode?: "FULL" | "EQUAL" | "ITEMS" | "CUSTOM";
            /** @constant */
            currency?: "VES";
            /**
             * @description What was divided. Every mode divides this same figure.
             * @example 756710
             */
            outstandingVes?: string;
            /**
             * @description Always equal to outstandingVes. Present so a client can assert it rather than trust it.
             * @example 756710
             */
            totalAllocatedVes?: string;
            allocations?: {
                participantId?: string;
                name?: string | null;
                /**
                 * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
                 * @example 756710
                 */
                amountVes?: string;
                usdReference?: string | null;
            }[];
        };
        /** @description A bill as a diner sees it. Narrower than Bill: internal identifiers and rate provenance are withheld, since this is the least trusted surface in the API. */
        GuestBill: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tableId?: string;
            /** @enum {string} */
            status?: "OPEN";
            /** @enum {string} */
            currency?: "VES" | "USD" | "EUR";
            /**
             * @description Sum of the line items, before charges.
             * @example 756710
             */
            subtotalMinor?: string;
            /** @description IVA rate in basis points, frozen when the bill opened. 1600 = 16%. */
            vatBps?: number;
            /**
             * @description IVA, taken on the subtotal alone — never on the service charge.
             * @example 756710
             */
            vatMinor?: string;
            /** @description Servicio rate in basis points, frozen when the bill opened. 1000 = 10%. */
            serviceChargeBps?: number;
            /**
             * @description Servicio, taken on the subtotal. Not taxed.
             * @example 756710
             */
            serviceChargeMinor?: string;
            /**
             * @description subtotalMinor + vatMinor + serviceChargeMinor, in the menu currency.
             * @example 756710
             */
            totalDue?: string;
            /**
             * @description Authoritative amount to settle.
             * @example 756710
             */
            totalDueVes?: string;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            amountPaidVes?: string;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            remainingVes?: string;
            /** @description Frozen when the bill opened. Present so a client can show an approximate menu-currency figure. */
            fxRateVesPerUnit?: string | null;
            usdReference?: components["schemas"]["UsdReference"];
            itemCount?: number;
            items?: components["schemas"]["BillItem"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        Table: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            restaurantId?: string;
            name?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        TableList: {
            data?: components["schemas"]["Table"][];
            limit?: number;
            offset?: number;
        };
        CreateTableRequest: {
            name: string;
        };
        UpdateTableRequest: {
            name?: string;
            active?: boolean;
        };
        Product: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            priceMinorUnits?: string;
            /** @enum {string} */
            currency?: "VES" | "USD" | "EUR";
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PublicProduct: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            priceMinorUnits?: string;
            /** @enum {string} */
            currency?: "VES" | "USD" | "EUR";
        };
        ProductList: {
            data?: components["schemas"]["Product"][];
            limit?: number;
            offset?: number;
        };
        /** @description The currency is taken from the restaurant menu currency and is not accepted here. */
        CreateProductRequest: {
            name: string;
            description?: string | null;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            priceMinorUnits: string;
            /** @default true */
            active: boolean;
        };
        UpdateProductRequest: {
            name?: string;
            description?: string | null;
            /**
             * @description Integer minor units (céntimos) as a string, so values beyond 2^53 survive JSON.
             * @example 756710
             */
            priceMinorUnits?: string;
            active?: boolean;
        };
        PublicMenu: {
            restaurant?: components["schemas"]["MenuSettings"];
            products?: components["schemas"]["PublicProduct"][];
        };
        MenuSettings: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            menuCurrency?: "VES" | "USD" | "EUR";
        };
        MenuCurrencyRequest: {
            /** @enum {string} */
            currency: "VES" | "USD" | "EUR";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        Session: {
            accessToken?: string;
            refreshToken?: string;
            expiresIn?: string;
            user?: components["schemas"]["SessionUser"];
        };
        /** @description The authenticated staff member. Returned by login, refresh and /auth/me alike, so a client stores one type. */
        SessionUser: {
            /** Format: uuid */
            id?: string;
            email?: string;
            /** @enum {string} */
            role?: "OWNER" | "MANAGER" | "CASHIER" | "WAITER";
            /** Format: uuid */
            restaurantId?: string;
        };
        GuestSessionRequest: {
            qrToken: string;
        };
        GuestSession: {
            /** Format: uuid */
            sessionId?: string;
            /** @description Returned once. Only a SHA-256 of it is stored, so it cannot be recovered later. */
            guestToken?: string;
            /** Format: uuid */
            restaurantId?: string;
            /** Format: uuid */
            tableId?: string;
            expiresIn?: number;
        };
        QrToken: {
            token?: string;
            expiresIn?: number;
        };
        ExchangeRate: {
            /** @description VES per unit of each supported currency. BCV publishes USD and EUR together. */
            rates?: {
                [key: string]: {
                    /**
                     * @description VES per unit, padded to 8 decimal places.
                     * @example 757.54060000
                     */
                    rate?: string;
                    /**
                     * Format: date
                     * @description The day the rate applies to, from BCV Fecha Valor. BCV publishes around 16:30 Caracas for the next business day, so this is not the fetch date.
                     */
                    valueDate?: string | null;
                    /** @example BCV */
                    source?: string;
                    /** Format: date-time */
                    fetchedAt?: string | null;
                };
            };
        };
        Liveness: {
            /** @constant */
            status?: "ok";
        };
        Readiness: {
            /** @enum {string} */
            status?: "ready" | "not_ready" | "shutting_down";
            /** @enum {string} */
            postgres?: "up" | "down";
            /** @enum {string} */
            redis?: "up" | "down";
        };
    };
    responses: {
        /** @description Validation failed, or the body contradicts the path. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
        /** @description Missing, malformed or expired credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but the role is not permitted, or the origin is not allowed by CORS. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource **inside the caller's restaurant**. A resource belonging to another tenant is reported as absent rather than forbidden, so the endpoint does not confirm it exists. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is valid but conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded, or the limiter is unavailable on a fail-closed surface. */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the window resets. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected failure. The message is never echoed; correlate using requestId. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A dependency is unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        BillId: string;
        TableId: string;
        BillItemId: string;
        ProductId: string;
        RestaurantId: string;
        Limit: number;
        Offset: number;
        /** @description Takes precedence over `idempotencyKey` in the body. Replaying a completed key returns the stored response instead of charging again; reusing a key with a different payload is a 409. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller. Identical in shape to `user` in a login or refresh response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: components["schemas"]["SessionUser"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getGuestBill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuestBill"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    previewGuestSplit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitPreviewRequest"];
            };
        };
        responses: {
            /** @description The allocation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    previewSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitPreviewRequest"];
            };
        };
        responses: {
            /** @description The allocation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    applyPayment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Takes precedence over `idempotencyKey` in the body. Replaying a completed key returns the stored response instead of charging again; reusing a key with a different payload is a 409. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["BillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Payment applied, or the stored response replayed for a repeated idempotency key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResult"];
                };
            };
            /** @description Validation failed, or `billId` does not match the path. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description One of: the payment exceeds the remaining balance; the bill is not OPEN; the idempotency key was reused with a different payload; or a request with that key is still in flight. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
}
