/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TasasRouteImport } from './routes/tasas'
import { Route as TpvHosteleriaRouteImport } from './routes/tpv-hosteleria'
import { Route as TIndexRouteImport } from './routes/t.index'
import { Route as TSplatRouteImport } from './routes/t.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TasasRoute = TasasRouteImport.update({
  id: '/tasas',
  path: '/tasas',
  getParentRoute: () => rootRouteImport,
} as any)
const TpvHosteleriaRoute = TpvHosteleriaRouteImport.update({
  id: '/tpv-hosteleria',
  path: '/tpv-hosteleria',
  getParentRoute: () => rootRouteImport,
} as any)
const TIndexRoute = TIndexRouteImport.update({
  id: '/t/',
  path: '/t/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSplatRoute = TSplatRouteImport.update({
  id: '/t/$',
  path: '/t/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pagos': typeof PagosRoute
  '/registro': typeof RegistroRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasas': typeof TasasRoute
  '/tpv-hosteleria': typeof TpvHosteleriaRoute
  '/t/$': typeof TSplatRoute
  '/t/': typeof TIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pagos': typeof PagosRoute
  '/registro': typeof RegistroRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasas': typeof TasasRoute
  '/tpv-hosteleria': typeof TpvHosteleriaRoute
  '/t/$': typeof TSplatRoute
  '/t': typeof TIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/pagos': typeof PagosRoute
  '/registro': typeof RegistroRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasas': typeof TasasRoute
  '/tpv-hosteleria': typeof TpvHosteleriaRoute
  '/t/$': typeof TSplatRoute
  '/t/': typeof TIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/pagos'
    | '/registro'
    | '/settings'
    | '/sitemap.xml'
    | '/tasas'
    | '/tpv-hosteleria'
    | '/t/$'
    | '/t/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/pagos'
    | '/registro'
    | '/settings'
    | '/sitemap.xml'
    | '/tasas'
    | '/tpv-hosteleria'
    | '/t/$'
    | '/t'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/pagos'
    | '/registro'
    | '/settings'
    | '/sitemap.xml'
    | '/tasas'
    | '/tpv-hosteleria'
    | '/t/$'
    | '/t/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  PagosRoute: typeof PagosRoute
  RegistroRoute: typeof RegistroRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasasRoute: typeof TasasRoute
  TpvHosteleriaRoute: typeof TpvHosteleriaRoute
  TSplatRoute: typeof TSplatRoute
  TIndexRoute: typeof TIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasas': {
      id: '/tasas'
      path: '/tasas'
      fullPath: '/tasas'
      preLoaderRoute: typeof TasasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpv-hosteleria': {
      id: '/tpv-hosteleria'
      path: '/tpv-hosteleria'
      fullPath: '/tpv-hosteleria'
      preLoaderRoute: typeof TpvHosteleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/': {
      id: '/t/'
      path: '/t'
      fullPath: '/t/'
      preLoaderRoute: typeof TIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$': {
      id: '/t/$'
      path: '/t/$'
      fullPath: '/t/$'
      preLoaderRoute: typeof TSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  PagosRoute: PagosRoute,
  RegistroRoute: RegistroRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasasRoute: TasasRoute,
  TpvHosteleriaRoute: TpvHosteleriaRoute,
  TSplatRoute: TSplatRoute,
  TIndexRoute: TIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
