/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvitacionRouteImport } from './routes/invitacion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TasasRouteImport } from './routes/tasas'
import { Route as TpvHosteleriaRouteImport } from './routes/tpv-hosteleria'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAltaRouteImport } from './routes/admin.alta'
import { Route as AdminCobrosRouteImport } from './routes/admin.cobros'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPreciosRouteImport } from './routes/admin.precios'
import { Route as RegistroVerificarRouteImport } from './routes/registro_.verificar'
import { Route as TIndexRouteImport } from './routes/t.index'
import { Route as TSplatRouteImport } from './routes/t.$'
import { Route as AdminClientesRestaurantIdRouteImport } from './routes/admin.clientes.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionRoute = InvitacionRouteImport.update({
  id: '/invitacion',
  path: '/invitacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TasasRoute = TasasRouteImport.update({
  id: '/tasas',
  path: '/tasas',
  getParentRoute: () => rootRouteImport,
} as any)
const TpvHosteleriaRoute = TpvHosteleriaRouteImport.update({
  id: '/tpv-hosteleria',
  path: '/tpv-hosteleria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAltaRoute = AdminAltaRouteImport.update({
  id: '/admin/alta',
  path: '/admin/alta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCobrosRoute = AdminCobrosRouteImport.update({
  id: '/admin/cobros',
  path: '/admin/cobros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreciosRoute = AdminPreciosRouteImport.update({
  id: '/admin/precios',
  path: '/admin/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroVerificarRoute = RegistroVerificarRouteImport.update({
  id: '/registro_/verificar',
  path: '/registro/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const TIndexRoute = TIndexRouteImport.update({
  id: '/t/',
  path: '/t/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSplatRoute = TSplatRouteImport.update({
  id: '/t/$',
  path: '/t/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRestaurantIdRoute =
  AdminClientesRestaurantIdRouteImport.update({
    id: '/admin/clientes/$restaurantId',
    path: '/admin/clientes/$restaurantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/invitacion': typeof InvitacionRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mesas': typeof MesasRoute
  '/pagos': typeof PagosRoute
  '/preview': typeof PreviewRoute
  '/registro': typeof RegistroRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasas': typeof TasasRoute
  '/tpv-hosteleria': typeof TpvHosteleriaRoute
  '/admin/alta': typeof AdminAltaRoute
  '/admin/cobros': typeof AdminCobrosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/registro/verificar': typeof RegistroVerificarRoute
  '/t/$': typeof TSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/t/': typeof TIndexRoute
  '/admin/clientes/$restaurantId': typeof AdminClientesRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/invitacion': typeof InvitacionRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mesas': typeof MesasRoute
  '/pagos': typeof PagosRoute
  '/preview': typeof PreviewRoute
  '/registro': typeof RegistroRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasas': typeof TasasRoute
  '/tpv-hosteleria': typeof TpvHosteleriaRoute
  '/admin/alta': typeof AdminAltaRoute
  '/admin/cobros': typeof AdminCobrosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/registro/verificar': typeof RegistroVerificarRoute
  '/t/$': typeof TSplatRoute
  '/admin': typeof AdminIndexRoute
  '/t': typeof TIndexRoute
  '/admin/clientes/$restaurantId': typeof AdminClientesRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/invitacion': typeof InvitacionRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mesas': typeof MesasRoute
  '/pagos': typeof PagosRoute
  '/preview': typeof PreviewRoute
  '/registro': typeof RegistroRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasas': typeof TasasRoute
  '/tpv-hosteleria': typeof TpvHosteleriaRoute
  '/admin/alta': typeof AdminAltaRoute
  '/admin/cobros': typeof AdminCobrosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/precios': typeof AdminPreciosRoute
  '/registro_/verificar': typeof RegistroVerificarRoute
  '/t/$': typeof TSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/t/': typeof TIndexRoute
  '/admin/clientes/$restaurantId': typeof AdminClientesRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invitacion'
    | '/login'
    | '/menu'
    | '/mesas'
    | '/pagos'
    | '/preview'
    | '/registro'
    | '/settings'
    | '/sitemap.xml'
    | '/tasas'
    | '/tpv-hosteleria'
    | '/admin/alta'
    | '/admin/cobros'
    | '/admin/login'
    | '/admin/precios'
    | '/registro/verificar'
    | '/t/$'
    | '/admin/'
    | '/t/'
    | '/admin/clientes/$restaurantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/invitacion'
    | '/login'
    | '/menu'
    | '/mesas'
    | '/pagos'
    | '/preview'
    | '/registro'
    | '/settings'
    | '/sitemap.xml'
    | '/tasas'
    | '/tpv-hosteleria'
    | '/admin/alta'
    | '/admin/cobros'
    | '/admin/login'
    | '/admin/precios'
    | '/registro/verificar'
    | '/t/$'
    | '/admin'
    | '/t'
    | '/admin/clientes/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/invitacion'
    | '/login'
    | '/menu'
    | '/mesas'
    | '/pagos'
    | '/preview'
    | '/registro'
    | '/settings'
    | '/sitemap.xml'
    | '/tasas'
    | '/tpv-hosteleria'
    | '/admin/alta'
    | '/admin/cobros'
    | '/admin/login'
    | '/admin/precios'
    | '/registro_/verificar'
    | '/t/$'
    | '/admin/'
    | '/t/'
    | '/admin/clientes/$restaurantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InvitacionRoute: typeof InvitacionRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MesasRoute: typeof MesasRoute
  PagosRoute: typeof PagosRoute
  PreviewRoute: typeof PreviewRoute
  RegistroRoute: typeof RegistroRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasasRoute: typeof TasasRoute
  TpvHosteleriaRoute: typeof TpvHosteleriaRoute
  AdminAltaRoute: typeof AdminAltaRoute
  AdminCobrosRoute: typeof AdminCobrosRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPreciosRoute: typeof AdminPreciosRoute
  RegistroVerificarRoute: typeof RegistroVerificarRoute
  TSplatRoute: typeof TSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TIndexRoute: typeof TIndexRoute
  AdminClientesRestaurantIdRoute: typeof AdminClientesRestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion': {
      id: '/invitacion'
      path: '/invitacion'
      fullPath: '/invitacion'
      preLoaderRoute: typeof InvitacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasas': {
      id: '/tasas'
      path: '/tasas'
      fullPath: '/tasas'
      preLoaderRoute: typeof TasasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tpv-hosteleria': {
      id: '/tpv-hosteleria'
      path: '/tpv-hosteleria'
      fullPath: '/tpv-hosteleria'
      preLoaderRoute: typeof TpvHosteleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alta': {
      id: '/admin/alta'
      path: '/admin/alta'
      fullPath: '/admin/alta'
      preLoaderRoute: typeof AdminAltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cobros': {
      id: '/admin/cobros'
      path: '/admin/cobros'
      fullPath: '/admin/cobros'
      preLoaderRoute: typeof AdminCobrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/precios': {
      id: '/admin/precios'
      path: '/admin/precios'
      fullPath: '/admin/precios'
      preLoaderRoute: typeof AdminPreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro_/verificar': {
      id: '/registro_/verificar'
      path: '/registro/verificar'
      fullPath: '/registro/verificar'
      preLoaderRoute: typeof RegistroVerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/': {
      id: '/t/'
      path: '/t'
      fullPath: '/t/'
      preLoaderRoute: typeof TIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$': {
      id: '/t/$'
      path: '/t/$'
      fullPath: '/t/$'
      preLoaderRoute: typeof TSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes/$restaurantId': {
      id: '/admin/clientes/$restaurantId'
      path: '/admin/clientes/$restaurantId'
      fullPath: '/admin/clientes/$restaurantId'
      preLoaderRoute: typeof AdminClientesRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InvitacionRoute: InvitacionRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MesasRoute: MesasRoute,
  PagosRoute: PagosRoute,
  PreviewRoute: PreviewRoute,
  RegistroRoute: RegistroRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasasRoute: TasasRoute,
  TpvHosteleriaRoute: TpvHosteleriaRoute,
  AdminAltaRoute: AdminAltaRoute,
  AdminCobrosRoute: AdminCobrosRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPreciosRoute: AdminPreciosRoute,
  RegistroVerificarRoute: RegistroVerificarRoute,
  TSplatRoute: TSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  TIndexRoute: TIndexRoute,
  AdminClientesRestaurantIdRoute: AdminClientesRestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
